### ISSUE TITLE
Key instanceof Array is failing

### ISSUE THREAD

**Issue by guerrillalg** [asmcrypto/asmcrypto.js#109]
Eventually, we are trying to use your library in our GWT project and have the following problem:
Line https://github.com/vibornoff/asmcrypto.js/blob/master/src/rsa/rsa.js#L17
`if ( key instanceof Array ) {`
Is failing the check and thus, we get an exception constantly. However, we pass a key as an Array.
After googling a while, I've found out the following:

> This approach will fail if obj was created in a different frame. Array.isArray doesn't have that issue if you can target EcmaScript5.

And indeed, GWT does some work in a different frame.
I've put the following code for an expirement:
`if ( Array.isArray(key) ) {`
And it did work fine for us.
So, the question is if you can use [Array.isArray](http://ecma-international.org/ecma-262/5.1/#sec-15.4.3.2) for the checks?

**Comment by vibornoff** [comment]
Does it compatible with IE10?

**Comment by guerrillalg** [comment]
Array methods are compatible with all browsers listed in the compatibility table:
[http://kangax.github.io/compat-table/es5/](http://kangax.github.io/compat-table/es5/)

**Comment by vibornoff** [comment]
Thanks, looks legit. But the problem is not only with `instanceof Array`.
Suitable replacement is need also for:
* `instanceof ArrayBuffer`: https://github.com/vibornoff/asmcrypto.js/blob/master/src/utils.js#L135-L137
* `instanceof Uint8Array`: https://github.com/vibornoff/asmcrypto.js/blob/master/src/utils.js#L139-L141
* `instanceof <TypedArray>`: https://github.com/vibornoff/asmcrypto.js/blob/master/src/utils.js#L143-L149 (`ArrayBuffer.isView` doesn't work with IE10 and probably Safary).

**Comment by guerrillalg** [comment]
For those methods, I can't say anything. Either they are not used in our case, or they work.
We use RSA encryption, SHA512 hashing and HMAC_SHA signing.

What are the system requirements?

**Comment by vibornoff** [comment]
IE10+, FF22+, Opera12+, Safari5.1+
